[project]
name = "number-neural-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "idx2numpy>=1.2.3",
    "numpy>=2.2.4",
]
